# <--------- Session-4 --------->

In [2]:
import pandas as pd

Task.1 :- Download a sample CSV file of IPL cricket match scores from Kaggle or any public dataset, and use pd.read_csv() to load it into a DataFrame. Print the first 5 rows to verify the data.

In [3]:
a = pd.read_csv(r"C:\PYTHON\Assignments-\Libraries\Session-4\deliveries.csv")

In [4]:
a.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

Task.2 :-Find a small JSON dataset of trending songs (for example, from Spotify's API samples or any open JSON file), and use pd.read_json() to import it into a DataFrame. Display the DataFrame's column names and data types using df.info().

In [5]:
b = pd.read_json(r"C:\PYTHON\Assignments-\Libraries\Session-4\data.json")

In [6]:
b.dtypes

title        str
artist       str
artwork      str
url          str
id         int64
dtype: object

Task.3 :- You have a TSV (tab-separated values) file containing Zomato restaurant data. Use pd.read_csv() with the correct separator to load the data, and then use df.describe(include='all') to generate summary statistics.<br><br><em><strong>Hint:</strong> The separator for TSV files is '\t'.</em>

In [7]:
df = pd.read_csv(r"C:\PYTHON\Assignments-\Libraries\Session-4\output-onlinetsvtools.tsv", sep = "\t")

In [8]:
df.describe(include="all")

,links\tnames\tratings\tcuisine\tprice,for,one,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
count,657,653,625,551,454,348,253,180,121,81,52,27,11,6,3,1
unique,657,453,316,223,190,129,97,76,62,48,32,23,11,6,3,1
top,https://www.zomato.com/hyderabad/sahara-bakers...,-,"Indian,","Indian,","Indian,","Indian,","Food,","Food,","Desserts,","Food,","Beverages,","Desserts,",Beverages\t100,"Food,",Beverages\t150,Beverages\t50
freq,1,22,34,54,40,29,21,17,10,6,7,3,1,1,1,1

Task.4 :- Download a large Excel file (at least 10,000 rows) of Flipkart product listings. Use pd.read_excel() with the chunksize parameter to read the file in chunks of 2000 rows, and print the number of rows in each chunk as you iterate.

In [9]:
d = pd.read_excel(r"C:\PYTHON\Assignments-\Libraries\Session-4\flipkart.xlsx")

In [10]:
d

,product_id,product_name,category,brand,seller,seller_city,price,discount_percent,final_price,rating,...,weight_g,warranty_months,color,size,return_policy_days,is_returnable,payment_modes,shipping_weight_g,product_score,seller_rating
0,FKP0000001,Adidas Ultra 664,Toys,Adidas,MegaStore,Hyderabad,35547.34,15,30215.24,1.9,...,3038.23,36,Green,XL,30,True,"COD,CARD",3483.592454,6.78,3.28
1,FKP0000002,LG Series 124,Fashion,LG,ValueKart,Mumbai,30693.79,10,27624.41,3.2,...,1921.82,0,Grey,One Size,7,True,"UPI,CARD",2091.473835,50.78,3.42
2,FKP0000003,Redmi Model 35,Beauty,Redmi,SmartDeals,Ahmedabad,51214.50,40,30728.70,4.4,...,1143.49,12,Black,M,0,False,"COD,UPI,CARD",1242.770494,4.24,4.23
3,FKP0000004,Sony Edition 769,Toys,Sony,UrbanRetails,Delhi,33168.49,30,23217.94,2.8,...,3644.81,24,Black,L,0,False,"CARD,Wallet",3891.222716,1.38,3.45
4,FKP0000005,Boat Prime 291,Home & Kitchen,Boat,RetailHub,Pune,14181.34,0,14181.34,3.7,...,310.33,0,Blue,NaN,30,True,"CARD,Wallet",386.061014,79.27,4.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,FKP0079996,Prestige Ultra 500,Sports,Prestige,MegaStore,Kolkata,42928.63,5,40782.20,1.1,...,3069.10,0,Gold,One Size,10,True,"UPI,CARD",3273.175933,20.07,4.88
79996,FKP0079997,Sony Prime 225,Mobiles,Sony,QuickShop,Ahmedabad,20158.55,10,18142.70,3.8,...,4412.53,0,Blue,M,30,True,"COD,CARD",5452.722633,6.97,4.57
79997,FKP0079998,LG Series 545,Beauty,LG,UrbanRetails,Kolkata,25317.70,20,20254.16,4.7,...,3114.32,0,Blue,S,7,True,"COD,UPI,CARD",3500.625634,1.28,4.15
79998,FKP0079999,Reebok Model 744,Toys,Reebok,MegaStore,Kolkata,7414.51,40,4448.71,4.3,...,3496.17,24,Gold,XL,30,True,"CARD,Wallet",3940.607738,5.06,3.63
79999,FKP0080000,Puma Ultra 650,Home & Kitchen,Puma,ValueKart,Kolkata,55472.95,30,38831.06,3.8,...,1858.88,6,Green,M,30,True,"CARD,Wallet",2082.266179,72.66,3.87

In [11]:
d[0:2000]

,product_id,product_name,category,brand,seller,seller_city,price,discount_percent,final_price,rating,...,weight_g,warranty_months,color,size,return_policy_days,is_returnable,payment_modes,shipping_weight_g,product_score,seller_rating
0,FKP0000001,Adidas Ultra 664,Toys,Adidas,MegaStore,Hyderabad,35547.34,15,30215.24,1.9,...,3038.23,36,Green,XL,30,True,"COD,CARD",3483.592454,6.78,3.28
1,FKP0000002,LG Series 124,Fashion,LG,ValueKart,Mumbai,30693.79,10,27624.41,3.2,...,1921.82,0,Grey,One Size,7,True,"UPI,CARD",2091.473835,50.78,3.42
2,FKP0000003,Redmi Model 35,Beauty,Redmi,SmartDeals,Ahmedabad,51214.50,40,30728.70,4.4,...,1143.49,12,Black,M,0,False,"COD,UPI,CARD",1242.770494,4.24,4.23
3,FKP0000004,Sony Edition 769,Toys,Sony,UrbanRetails,Delhi,33168.49,30,23217.94,2.8,...,3644.81,24,Black,L,0,False,"CARD,Wallet",3891.222716,1.38,3.45
4,FKP0000005,Boat Prime 291,Home & Kitchen,Boat,RetailHub,Pune,14181.34,0,14181.34,3.7,...,310.33,0,Blue,NaN,30,True,"CARD,Wallet",386.061014,79.27,4.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,FKP0001996,Reebok Series 376,Mobiles,Reebok,MegaStore,Hyderabad,41991.04,5,39891.49,4.8,...,1674.75,12,White,One Size,10,True,"COD,CARD",1956.145081,45.06,3.88
1996,FKP0001997,LG Edition 818,Electronics,LG,QuickShop,Pune,3163.91,0,3163.91,4.9,...,857.06,12,White,XL,0,False,"CARD,Wallet",1024.574840,45.82,4.47
1997,FKP0001998,LG Prime 817,Mobiles,LG,ValueKart,Bengaluru,30779.81,40,18467.89,3.8,...,4383.41,24,Silver,XL,0,False,"COD,CARD",5123.183979,11.67,4.60
1998,FKP0001999,LG Model 253,Toys,LG,SuperMart,Hyderabad,10632.72,20,8506.18,2.3,...,2995.90,0,Black,S,0,False,"CARD,Wallet",3470.388767,15.43,4.21
1999,FKP0002000,Philips Model 612,Mobiles,Philips,BestBuy,Bengaluru,42793.60,10,38514.24,1.6,...,3937.43,0,Black,NaN,7,True,"CARD,Wallet",4875.577608,55.70,3.20

Task.5 :- Use ChatGPT or Copilot to generate a Python code snippet that reads a semicolon-separated CSV of Paytm transactions, detects missing values, and prints out which columns have nulls. Test the code with a small sample file and fix any errors you encounter.

In [12]:
df = pd.read_csv(r"C:\PYTHON\Assignments-\Libraries\Session-4\business.csv")

In [13]:
df

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,BDCQ.SF1AA2CA,2016.06,1116.386,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 2),Sales (operating income),Forestry and Logging,Current prices,Unadjusted,NaN
1,BDCQ.SF1AA2CA,2016.09,1070.874,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 2),Sales (operating income),Forestry and Logging,Current prices,Unadjusted,NaN
2,BDCQ.SF1AA2CA,2016.12,1054.408,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 2),Sales (operating income),Forestry and Logging,Current prices,Unadjusted,NaN
3,BDCQ.SF1AA2CA,2017.03,1010.665,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 2),Sales (operating income),Forestry and Logging,Current prices,Unadjusted,NaN
4,BDCQ.SF1AA2CA,2017.06,1233.700,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 2),Sales (operating income),Forestry and Logging,Current prices,Unadjusted,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9550,BDCQ.SF8RSCA,2025.03,699.681,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 1),Operating profit,"Arts, Recreation and Other Services",Current,Unadjusted,NaN
9551,BDCQ.SF8RSCA,2025.06,587.843,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 1),Operating profit,"Arts, Recreation and Other Services",Current,Unadjusted,NaN
9552,BDCQ.SF8RSCA,2025.09,658.866,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 1),Operating profit,"Arts, Recreation and Other Services",Current,Unadjusted,NaN
9553,BDCQ.SF8RSCA,2025.12,734.757,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 1),Operating profit,"Arts, Recreation and Other Services",Current,Unadjusted,NaN
9554,BDCQ.SF8RSCA,2026.03,884.011,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 1),Operating profit,"Arts, Recreation and Other Services",Current,Unadjusted,NaN

In [14]:
print(df.isnull().sum())
null_columns = df.columns[df.isnull().any()].tolist()

if null_columns:
    print("\nColumns containing null values:")
    for col in null_columns:
        print(f"- {col}")
else:
    print("\nNo null values found.")

Series_reference       0
Period                 0
Data_value            45
Suppressed          9540
STATUS                 0
UNITS                  0
Magnitude              0
Subject                0
Group                  0
Series_title_1         0
Series_title_2         0
Series_title_3         0
Series_title_4         0
Series_title_5      9555
dtype: int64

Columns containing null values:
- Data_value
- Suppressed
- Series_title_5