# <--------- Session-5 --------->

Task.1 :- Connect to a MySQL or PostgreSQL database using SQLAlchemy and pandas, then use pd.read_sql() to load the entire 'restaurants' table (imagine Zomato backend) into a DataFrame and display the first 5 rows.

In [2]:
# remainind sql

Task.2 :- Use pd.read_sql_query() to fetch only the 'name' and 'rating' columns from a 'movies' table (think BookMyShow-like data) where rating is above 8, and print the resulting DataFrame.<br><br><em><strong>Hint:</strong> Write a custom SQL SELECT query as the first argument to pd.read_sql_query().</em>

In [3]:
# remainind sql

Task.3 :- Read a JSON dataset from the URL https://jsonplaceholder.typicode.com/users using pandas, convert it into a DataFrame, and print the usernames column.<br><br><em><strong>Hint:</strong> Use pd.read_json() directly with the URL.</em>

In [4]:
import pandas as pd

In [23]:
df = pd.read_json("https://jsonplaceholder.typicode.com/users")
df

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

In [10]:
df["username"]

0                Bret
1           Antonette
2            Samantha
3            Karianne
4              Kamren
5    Leopoldo_Corkery
6        Elwyn.Skiles
7       Maxime_Nienow
8            Delphine
9      Moriah.Stanton
Name: username, dtype: str

Task.4 :- You have two CSV files: 'orders.csv' (order_id, user_id, amount) and 'users.csv' (user_id, username). Load both into DataFrames using pathlib for file paths, then merge them on 'user_id' to show a combined table with username and amount.

In [40]:
df1 = pd.read_csv(r"C:\PYTHON\Assignments-\Libraries\Session-5\users.csv")
df2 = pd.read_csv(r"C:\PYTHON\Assignments-\Libraries\Session-5\orders.csv")

In [41]:
df1

     user_id  username
0          1    user_1
1          2    user_2
2          3    user_3
3          4    user_4
4          5    user_5
..       ...       ...
495      496  user_496
496      497  user_497
497      498  user_498
498      499  user_499
499      500  user_500

[500 rows x 2 columns]

In [42]:
df2

     order_id  user_id  amount
0        1001      328    1846
1        1002       58    4244
2        1003       13    2272
3        1004      380    1185
4        1005      141    2959
..        ...      ...     ...
495      1496      319    1802
496      1497      289    1828
497      1498       52    2267
498      1499       38     765
499      1500      276    1386

[500 rows x 3 columns]

In [43]:
pd.merge(df1,df2)

     user_id  username  order_id  amount
0        350  user_350      1107    1044
1        326  user_326      1111    2274
2        260  user_260      1223    2059
3         48   user_48      1020    2266
4        369  user_369      1217    3786
..       ...       ...       ...     ...
495       33   user_33      1304    2966
496       25   user_25      1175    1940
497      149  user_149      1087    1922
498      113  user_113      1169    2424
499      289  user_289      1497    1828

[500 rows x 4 columns]

Task.5 :-Concatenate two DataFrames representing 'today_orders' and 'yesterday_orders' (each with columns: order_id, item, price), and display the combined DataFrame.<br><br><em><strong>Constraint:</strong> Use pd.concat() and reset the index after concatenation.</em>

In [12]:
a = {
    "order_id": ["to_1028","to_1029","to_1030"],
    "item": ["Manchurian","Pizza","Burger"],
    "price": [150,650,200]
}

b= {
    "order_id": ["yo_1028","yo_1029","yo_1030"],
    "item": ["Momos","Noodles","Bread Pakoda"],
    "price": [130,450,300]
}

In [18]:
today_order = pd.DataFrame(a)
yesterday_order = pd.DataFrame(b)
print(today_order)

print("\n",yesterday_order)

  order_id        item  price
0  to_1028  Manchurian    150
1  to_1029       Pizza    650
2  to_1030      Burger    200

   order_id          item  price
0  yo_1028         Momos    130
1  yo_1029       Noodles    450
2  yo_1030  Bread Pakoda    300

In [ ]:
df3 = pd.concat([today_order,yesterday_order],axis = 0)
df3

  order_id          item  price
0  to_1028    Manchurian    150
1  to_1029         Pizza    650
2  to_1030        Burger    200
0  yo_1028         Momos    130
1  yo_1029       Noodles    450
2  yo_1030  Bread Pakoda    300

In [ ]:
df3.reset_index()

   index order_id          item  price
0      0  to_1028    Manchurian    150
1      1  to_1029         Pizza    650
2      2  to_1030        Burger    200
3      0  yo_1028         Momos    130
4      1  yo_1029       Noodles    450
5      2  yo_1030  Bread Pakoda    300